version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/DockerData/Shop/RabbitMq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=01031990Pc

  sqlserver:
    image: microsoft/mssql-server-linux:2017-CU12
    container_name: sqlserver
    volumes:
      - sqlserverdata:/DockerData/Shop/SqlServer
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=01031990Pc

  mailserver:
    image: djfarrelly/maildev
    container_name: mailserver
    ports:
      - "25:25"
      - "4000:80"
  
  logserver:
    image: datalust/seq:5
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  productsearchservice.api:
    image: shop/productsearchservice.api:latest
    build: ProductSearchService/ProductSearchService.API
    container_name: productsearchservice.api
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  productsearchservice.eventlistener:
    image: shop/productsearchservice.eventlistener:latest
    build: ProductSearchService/ProductSearchService.EventListener
    container_name: productsearchservice.eventlistener
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - SHOP_ENVIRONMENT=Production

volumes:
  sqlserverdata:
    external: true    
  rabbitmqdata:
    external: true