version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - data.rabbitmq:/data
      - log.rabbitmq:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=01031990Pc

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=elastic-shop-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - discovery.zen.hosts_provider=file
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data.elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - data.redis:/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

  productsearchservice.api:
    image: shop/productsearchservice.api:latest
    build: ProductSearchService/ProductSearchService.API/ProductSearchService.API
    container_name: productsearchservice.api
    depends_on:
      - rabbitmq
      - elastic
      - redis
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  data.elastic:
  data.rabbitmq:
  log.rabbitmq:
  data.redis:
