version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - data.rabbitmq:/DockerData/Shop/RabbitMq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=01031990Pc

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elastic
    environment:
      - cluster.name=elastic-shop-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512 -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data.elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: kibana
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
  
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:6.7.0
    container_name: heartbeat
    volumes:
      - './heartbeat.yml:/usr/share/heartbeat/heartbeat.yml'
    depends_on:
      - elastic
      - kibana
    environment:
      - setup.kibana.host=kibana:5601
      - setup.elasticsearch.hosts=["elastic:9200"]
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.7.0
    container_name: metricbeat
    volumes:
      - './metricbeat.yml:/usr/share/metricbeat/metricbeat.yml'
    environment:
      - ELASTICSEARCH_HOST=elastic:9200
      - KIBANA_HOST=kibana:5601

  mailserver:
    image: djfarrelly/maildev
    container_name: mailserver
    ports:
      - "25:25"
      - "4000:80"
  
  logserver:
    image: datalust/seq:5
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  productsearchservice.api:
    image: shop/productsearchservice.api:latest
    build: ProductSearchService/ProductSearchService.API
    container_name: productsearchservice.api
    depends_on:
      - rabbitmq
      - elastic
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  productsearchservice.eventlistener:
    image: shop/productsearchservice.eventlistener:latest
    build: ProductSearchService/ProductSearchService.EventListener
    container_name: productsearchservice.eventlistener
    depends_on:
      - rabbitmq
      - elastic
    environment:
      - SHOP_ENVIRONMENT=Production

volumes:
  data.elastic:
    external: true
  data.rabbitmq:
    external: true