heartbeat.monitors:
  - type: http
    schedule: '@every 5s'
    urls: ["http://elastic:9200"]

output.elasticsearch:
  hosts: ["http://elastic:9200"]
  index: "heartbeat-%{[beat.version]}-%{+yyyy.MM.dd}"

setup.template:
  name: "heartbeat"
  pattern: "heartbeat-*"
  enabled: false

setup.kibana:
  host: "http://kibana:5601"